categories:
  - name: "论文"
    description: "记录论文或者研究的名字，然后整理一个简单的论文总结"
  - name: "活动"
    description: “活动信息，需要记录活动的事件内容，事件和地点”
  - name: "经验"
    description: ”关于做某些事情的经验，要求先做个分类是什么类型的经验（学习，求职等），然后再做总结“